# -*- coding: utf-8 -*-
"""Final_Project_BookSales_Lisa_Luiten

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ui9RSJjwphIjvwhUjoQ2qMy9KonmjiV2

# How are book sales impacted by different factors? (author skill, rating)

# Data Overview and EDA
"""

import pandas as pd

books_df = pd.read_csv('/content/Books_Data_Clean.csv')

books_df.shape

books_df.head(3)

books_df.info()

"""It appears that 'lanuguage_code' is missing 49 data values. I will not be utilizing language_code in this analysis, however.

The data types all seem to be accurate.
"""

# Changing column names for ease of use
books_df.columns = books_df.columns.str.replace(' ', '_').str.lower()

books_df.columns

books_df.describe()

books_df.value_counts('genre')

books_df.value_counts('author_rating')

books_df.groupby('genre').mean(numeric_only=True)

books_df.groupby('author_rating').mean(numeric_only=True)

"""This data includes information on the sales of books, presumably from a book retailer. It includes information on book name, author, author skill, book rating, and sales information.

# **Core Python Constructs**
"""

# Separate the highly rated books into their own list
highly_rated_books = [book for book in books_df['book_name'] if books_df.loc[books_df['book_name'] == book, 'book_average_rating'].iloc[0] > 4.5]

highly_rated_books

# Defining a function to calculate revenue
def calculate_revenue(sale_price, units_sold):
  return sale_price * units_sold

books_df['revenue'] = calculate_revenue(books_df['sale_price'], books_df['units_sold'])

books_df.head(3)

"""# Data Visualizations"""

import seaborn as sns
import matplotlib.pyplot as plt

sns.displot(books_df['book_average_rating'], rug=True,
            rug_kws={'color':'r', 'height':0.07},
            alpha=0.5)

plt.axvline(books_df['book_average_rating'].median(), color = 'red')
plt.title('Average Book Rating Frequency Histogram')
plt.xlabel('Average Rating')
plt.ylabel('Frequency');

"""Based on the histogram, you can see that most ratings fell between 3.75 and 4.25, which is relatively high. The median rating is very close to 4.00."""

sns.boxplot(x=books_df['author_rating'], y=books_df['units_sold'], notch=True)


sns.despine()

"""In the above box plot, it appears that the median units sold did not widely vary amongst author skill ratings. Excellent group did have the widest spread in units sold. Excellent authors sold the most units, however. It would seem that authors in the excellent category have the most units sold, compared to other skill levels."""

plt.bar(books_df['author_rating'], books_df['revenue'], color='b')

plt.title('Revenue by Author Skill')
plt.xlabel('Author Skill Rating')
plt.ylabel('Revenue')

"""This bar chart shows that excellent rated authors brought in the most profit in book sales. This was followed by intermediate authors. This shows that the author's skill seems to have an impact on book sales, but famous authors don't necessarily bring in the most profit."""

sns.regplot(x=books_df['book_average_rating'], y=books_df['units_sold'], data=books_df)

sns.despine()

"""There is a big separation in the data, with a split between units sold of about 30,000 and more and 10,000 and less. There is no clear trend line beween book rating and units sold, indicated by the very flat trend line. It seems that book rating does not have an impact on units sold."""

sns.lineplot(x='author_rating', y='book_average_rating', data=books_df)
plt.title("Author Rating vs. Average Book Rating")
plt.xlabel("Author Rating")
plt.ylabel("Average Book Rating")
sns.despine()
plt.show()

"""This chart shows the correlation between author rating and book rating. It seems like famous authors' books tend to receive higher ratings, whereas novice authors receive the lowest average ratings.

# Conclusion and Findings

Based on the evaluations, we were able to find some correlations between author and book characteristics and their impacts on book sales.

In the line chart, we see that famous authors receive the highest average book ratings by readers while novice authors receive the lowest. However, interestingly, these high ratings do not seem to be correlated with higher book sales.

In the scatter plot, we did not find a correlation between book rating and units sold. However, we did find a correlation between author skill rating and profit. And, while famous authors had the highest rated books, they came in third place in terms of profit. Excellent and intermediate rated authors surpassed famous authors in terms of profit.

Finally, based on the box plot, we see that excellent rated authors have the widest spread in terms of units sold. The other three skill groups were relatively consistent in terms of spread. However, the median of all groups were not significantly different.

Final Takeaways:
1. Famous authors' books rate the highest but they do not sell the most units
2. Excellent authors' books bring in the most revenue, followed by intermediate authors.
3. Books are rated fairly generously, based on this data. The median score was about 4.00 with most ratings falling beween 3.75 and 4.25.
4. However, there was no clear correlation between book ratings and units sold.

Futher research:

Which genres performed the best?

Why do excellent authors bring in more revenue? (appealing book pricing, marketing, more books produced, etc?)
"""

!jupyter nbconvert --to html "/content/Final_Project_BookSales_Lisa_Luiten.ipynb"